# Generated by Django 2.2 on 2019-04-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('social', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'leads'), (2, 'calls'), (3, 'recalls'), (4, 'meetings'), (5, 'blocks')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(blank=True, null=True)),
                ('call_status', models.IntegerField(choices=[(0, 'Call pending'), (1, 'Call answered'), (2, 'Call unanswered'), (6, 'Call rescheduled'), (3, 'Recall pending'), (4, 'Recall answered'), (5, 'Recall unanswered'), (7, 'Recall rescheduled')], default=0)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_status', models.IntegerField(choices=[(1, 'Meeting pending'), (2, 'Meeting accomplished'), (3, 'Meeting rescheduled'), (4, 'Meeting canceled')], default=1)),
                ('met_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.Lead')),
            ],
        ),
    ]
