# Generated by Django 2.2 on 2019-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20190422_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LeadInteraction',
        ),
    ]
